version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: synaptix-db
    environment:
      POSTGRES_DB: isp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - ./isp_postgres.sql:/docker-entrypoint-initdb.d/1-init.sql:z
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
