package com.synaptix.isp;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.time.Second;
import org.jfree.data.time.TimeSeries;
import org.jfree.data.time.TimeSeriesCollection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hunter Fox
 */
public class Admin extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
ResultSet rs;
private javax.swing.JLabel lblActiveCustomersVal;
private javax.swing.JLabel lblRevenueVal;
private javax.swing.JLabel lblComplaintsVal;
private javax.swing.JPanel chartPanel;
private javax.swing.JLabel lblLiveDl;
private javax.swing.JLabel lblLiveUl;
private javax.swing.JLabel lblLivePing;
private org.jfree.data.time.TimeSeries downloadSeries;
private org.jfree.data.time.TimeSeries uploadSeries;
private javax.swing.Timer monitorTimer;
private long[] lastBytes;
private double lastDlSim = 45.0;
private double lastUlSim = 20.0;
    public Admin() {
        super("Admin Panel");
        initComponents();
        conn=javaconnect.ConnecrDb();
        showDate();
        showTime();
        setupDashboardLayout();
    }

     void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("YYYY-MM-dd");
        dateLab.setText(s.format(d));
    }
    
    void showTime(){
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
        timeLab.setText(s.format(d));
            }
        }).start();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateLab = new javax.swing.JTextField();
        timeLab = new javax.swing.JTextField();
        btnPlan = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnComplain = new javax.swing.JButton();
        btnEmp = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SynapTix Broadband - Admin Dashboard");
        setResizable(true);

        // Main Panel (Background) - GridBagLayout for centering
        jPanel1.setBackground(new java.awt.Color(240, 244, 248));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        // Header Panel (Top Bar)
        javax.swing.JPanel headerPanel = new javax.swing.JPanel();
        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 25));
        headerPanel.setLayout(new java.awt.BorderLayout());

        // Header Left (Logo + Title)
        javax.swing.JPanel headerLeft = new javax.swing.JPanel();
        headerLeft.setOpaque(false);
        headerLeft.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 0));
        
        java.net.URL logoUrl = getClass().getResource("/logomain.png");
        if (logoUrl != null) {
            javax.swing.ImageIcon logoIcon = new javax.swing.ImageIcon(logoUrl);
            java.awt.Image scaledLogo = logoIcon.getImage().getScaledInstance(55, 55, java.awt.Image.SCALE_SMOOTH);
            jLabel4.setIcon(new javax.swing.ImageIcon(scaledLogo));
        } else {
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logomain.png")));
        }
        headerLeft.add(jLabel4);

        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22));
        jLabel1.setForeground(new java.awt.Color(33, 43, 54));
        jLabel1.setText("SYNAPTIX BROADBAND");
        headerLeft.add(jLabel1);
        headerPanel.add(headerLeft, java.awt.BorderLayout.WEST);

        // Header Right (Date & Time)
        javax.swing.JPanel headerRight = new javax.swing.JPanel();
        headerRight.setOpaque(false);
        headerRight.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 5));

        jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        jLabel2.setForeground(new java.awt.Color(99, 115, 129));
        jLabel2.setText("Date:");
        headerRight.add(jLabel2);

        dateLab.setEditable(false);
        dateLab.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        dateLab.setColumns(8);
        headerRight.add(dateLab);

        jLabel3.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        jLabel3.setForeground(new java.awt.Color(99, 115, 129));
        jLabel3.setText("Time:");
        headerRight.add(jLabel3);

        timeLab.setEditable(false);
        timeLab.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        timeLab.setColumns(8);
        headerRight.add(timeLab);
        headerPanel.add(headerRight, java.awt.BorderLayout.EAST);

        // Admin Card Container
        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224), 1),
            javax.swing.BorderFactory.createEmptyBorder(30, 40, 30, 40)
        ));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.insets = new java.awt.Insets(0, 0, 10, 0);
        gbc.anchor = java.awt.GridBagConstraints.CENTER;

        jLabel5.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        jLabel5.setForeground(new java.awt.Color(33, 43, 54));
        jLabel5.setText("ADMIN DASHBOARD");
        jPanel2.add(jLabel5, gbc);

        gbc.gridy = 1;
        gbc.insets = new java.awt.Insets(0, 0, 30, 0);
        btnLogout.setBackground(new java.awt.Color(239, 68, 68));
        btnLogout.putClientProperty("JButton.buttonType", "roundRect");
        btnLogout.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png")));
        btnLogout.setText("LOG OUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, gbc);

        // Grid of options
        gbc.gridwidth = 1;
        gbc.insets = new java.awt.Insets(10, 10, 10, 10);
        gbc.fill = java.awt.GridBagConstraints.BOTH;
        gbc.weightx = 0.5;
        gbc.weighty = 0.5;

        // Button: Create Plan
        gbc.gridx = 0;
        gbc.gridy = 2;
        btnPlan.setBackground(new java.awt.Color(37, 99, 235));
        btnPlan.putClientProperty("JButton.buttonType", "roundRect");
        btnPlan.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        btnPlan.setForeground(new java.awt.Color(255, 255, 255));
        btnPlan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newplan.png")));
        btnPlan.setText("CREATE PLAN");
        btnPlan.setPreferredSize(new java.awt.Dimension(220, 60));
        btnPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanActionPerformed(evt);
            }
        });
        jPanel2.add(btnPlan, gbc);

        // Button: Customer
        gbc.gridx = 1;
        gbc.gridy = 2;
        btnCustomer.setBackground(new java.awt.Color(37, 99, 235));
        btnCustomer.putClientProperty("JButton.buttonType", "roundRect");
        btnCustomer.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        btnCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer.png")));
        btnCustomer.setText("CUSTOMER");
        btnCustomer.setPreferredSize(new java.awt.Dimension(220, 60));
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        jPanel2.add(btnCustomer, gbc);

        // Button: Employees
        gbc.gridx = 0;
        gbc.gridy = 3;
        btnEmp.setBackground(new java.awt.Color(37, 99, 235));
        btnEmp.putClientProperty("JButton.buttonType", "roundRect");
        btnEmp.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        btnEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee.png")));
        btnEmp.setText("EMPLOYEES");
        btnEmp.setPreferredSize(new java.awt.Dimension(220, 60));
        btnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmp, gbc);

        // Button: Complaint
        gbc.gridx = 1;
        gbc.gridy = 3;
        btnComplain.setBackground(new java.awt.Color(37, 99, 235));
        btnComplain.putClientProperty("JButton.buttonType", "roundRect");
        btnComplain.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        btnComplain.setForeground(new java.awt.Color(255, 255, 255));
        btnComplain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complaint.png")));
        btnComplain.setText("COMPLAINT");
        btnComplain.setPreferredSize(new java.awt.Dimension(220, 60));
        btnComplain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplainActionPerformed(evt);
            }
        });
        jPanel2.add(btnComplain, gbc);

        // Layout assemblies in main content
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);
        
        java.awt.GridBagConstraints mainGbc = new java.awt.GridBagConstraints();
        mainGbc.gridx = 0;
        mainGbc.gridy = 0;
        mainGbc.insets = new java.awt.Insets(40, 40, 40, 40);
        mainGbc.anchor = java.awt.GridBagConstraints.CENTER;
        jPanel1.add(jPanel2, mainGbc);
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setSize(960, 680);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanActionPerformed
        stopMonitorTimer();
        try { if (conn != null) conn.close(); } catch(Exception e){}
        CreatePlan ob=new CreatePlan();
        ob.inheritWindowState(this);
        ob.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dispose();
            }
        });
    }//GEN-LAST:event_btnPlanActionPerformed

    private void btnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpActionPerformed
        stopMonitorTimer();
        try { if (conn != null) conn.close(); } catch(Exception e){}
        Employee ob=new Employee();
        ob.inheritWindowState(this);
        ob.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dispose();
            }
        });
    }//GEN-LAST:event_btnEmpActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        stopMonitorTimer();
        try { if (conn != null) conn.close(); } catch(Exception e){}
        Customer ob=new Customer();
        ob.inheritWindowState(this);
        ob.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dispose();
            }
        });
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnComplainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplainActionPerformed
        stopMonitorTimer();
        try { if (conn != null) conn.close(); } catch(Exception e){}
        Complaint ob=new Complaint();
        ob.inheritWindowState(this);
        ob.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dispose();
            }
        });
    }//GEN-LAST:event_btnComplainActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        stopMonitorTimer();
        try { if (conn != null) conn.close(); } catch(Exception e){}
        Home ob=new Home();
        ob.inheritWindowState(this);
        ob.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dispose();
            }
        });
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void dateLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateLabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComplain;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnEmp;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPlan;
    private javax.swing.JTextField dateLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField timeLab;
    // End of variables declaration//GEN-END:variables

    private void setupDashboardLayout() {
        jPanel1.removeAll();
        jPanel1.setLayout(new java.awt.BorderLayout(20, 20));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 25, 20, 25));

        // Style header Date & Time text fields to be flat and borderless
        dateLab.setBorder(null);
        dateLab.setOpaque(false);
        dateLab.setBackground(new java.awt.Color(255, 255, 255));
        dateLab.setFocusable(false);
        
        timeLab.setBorder(null);
        timeLab.setOpaque(false);
        timeLab.setBackground(new java.awt.Color(255, 255, 255));
        timeLab.setFocusable(false);

        // Stats Panel at top
        javax.swing.JPanel statsPanel = new javax.swing.JPanel();
        statsPanel.setOpaque(false);
        statsPanel.setLayout(new java.awt.GridLayout(1, 3, 20, 0)); // 3 cards side-by-side

        javax.swing.JPanel cardCustomers = createStatCard("Active Customers", lblActiveCustomersVal = new javax.swing.JLabel("0"), new java.awt.Color(37, 99, 235));
        javax.swing.JPanel cardRevenue = createStatCard("Monthly Revenue", lblRevenueVal = new javax.swing.JLabel("Rs. 0.00"), new java.awt.Color(16, 185, 129));
        javax.swing.JPanel cardComplaints = createStatCard("Complaints Solved", lblComplaintsVal = new javax.swing.JLabel("0 / 0"), new java.awt.Color(245, 158, 11));

        statsPanel.add(cardCustomers);
        statsPanel.add(cardRevenue);
        statsPanel.add(cardComplaints);
        
        jPanel1.add(statsPanel, java.awt.BorderLayout.NORTH);

        // Left side: jPanel2 (Navigation Panel) - wrapped to prevent vertical stretching
        javax.swing.JPanel leftWrapper = new javax.swing.JPanel(new java.awt.BorderLayout());
        leftWrapper.setOpaque(false);
        leftWrapper.add(jPanel2, java.awt.BorderLayout.NORTH);
        
        jPanel1.add(leftWrapper, java.awt.BorderLayout.WEST);

        // Right side: Tabbed Pane container
        javax.swing.JTabbedPane tabbedPane = new javax.swing.JTabbedPane();
        tabbedPane.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));

        // Tab 1: Plan Distribution (Pie Chart)
        chartPanel = new javax.swing.JPanel();
        chartPanel.setBackground(java.awt.Color.WHITE);
        chartPanel.setLayout(new java.awt.BorderLayout());
        tabbedPane.addTab("Plan Analytics", chartPanel);

        // Tab 2: Live Network Monitor (Dynamic Line Chart + Readouts)
        javax.swing.JPanel liveMonitorPanel = new javax.swing.JPanel();
        liveMonitorPanel.setBackground(java.awt.Color.WHITE);
        liveMonitorPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.JPanel liveChartContainer = new javax.swing.JPanel();
        liveChartContainer.setBackground(java.awt.Color.WHITE);
        liveChartContainer.setLayout(new java.awt.BorderLayout());
        liveMonitorPanel.add(liveChartContainer, java.awt.BorderLayout.CENTER);

        javax.swing.JPanel readoutsPanel = new javax.swing.JPanel();
        readoutsPanel.setBackground(new java.awt.Color(248, 250, 252));
        readoutsPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(226, 232, 240)));
        readoutsPanel.setLayout(new java.awt.GridLayout(1, 3, 10, 0));
        readoutsPanel.setPreferredSize(new java.awt.Dimension(0, 60));

        lblLiveDl = new javax.swing.JLabel("0.0 Gbps", javax.swing.SwingConstants.CENTER);
        lblLiveUl = new javax.swing.JLabel("0.0 Gbps", javax.swing.SwingConstants.CENTER);
        lblLivePing = new javax.swing.JLabel("0 ms", javax.swing.SwingConstants.CENTER);

        readoutsPanel.add(createReadoutComponent("DOWNLOAD LOAD", lblLiveDl, new java.awt.Color(37, 99, 235)));
        readoutsPanel.add(createReadoutComponent("UPLOAD LOAD", lblLiveUl, new java.awt.Color(16, 185, 129)));
        readoutsPanel.add(createReadoutComponent("LATENCY (PING)", lblLivePing, new java.awt.Color(139, 92, 246)));

        liveMonitorPanel.add(readoutsPanel, java.awt.BorderLayout.SOUTH);
        tabbedPane.addTab("NOC Live Monitor", liveMonitorPanel);

        // Tab 3: System Utilities (Backup, Restore, Change Password, Export Report)
        javax.swing.JPanel systemUtilitiesPanel = new javax.swing.JPanel();
        systemUtilitiesPanel.setBackground(java.awt.Color.WHITE);
        systemUtilitiesPanel.setLayout(new java.awt.GridLayout(1, 3, 15, 0));

        // Card 1: Database Utilities
        javax.swing.JPanel dbUtilsCard = new javax.swing.JPanel();
        dbUtilsCard.setBackground(java.awt.Color.WHITE);
        dbUtilsCard.setBorder(javax.swing.BorderFactory.createTitledBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 232, 240), 1),
            "DATABASE UTILITIES",
            javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
            javax.swing.border.TitledBorder.DEFAULT_POSITION,
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12),
            new java.awt.Color(71, 85, 105)
        ));
        dbUtilsCard.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints dbGbc = new java.awt.GridBagConstraints();
        dbGbc.insets = new java.awt.Insets(15, 15, 15, 15);
        dbGbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        dbGbc.weightx = 1.0;
        dbGbc.gridx = 0;

        javax.swing.JButton btnBackup = new javax.swing.JButton("BACKUP DATABASE");
        btnBackup.setBackground(new java.awt.Color(37, 99, 235));
        btnBackup.setForeground(java.awt.Color.WHITE);
        btnBackup.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btnBackup.setPreferredSize(new java.awt.Dimension(200, 45));
        btnBackup.putClientProperty("JButton.buttonType", "roundRect");
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });
        dbGbc.gridy = 0;
        dbUtilsCard.add(btnBackup, dbGbc);

        javax.swing.JButton btnRestore = new javax.swing.JButton("RESTORE DATABASE");
        btnRestore.setBackground(new java.awt.Color(37, 99, 235));
        btnRestore.setForeground(java.awt.Color.WHITE);
        btnRestore.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btnRestore.setPreferredSize(new java.awt.Dimension(200, 45));
        btnRestore.putClientProperty("JButton.buttonType", "roundRect");
        btnRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoreActionPerformed(evt);
            }
        });
        dbGbc.gridy = 1;
        dbUtilsCard.add(btnRestore, dbGbc);

        systemUtilitiesPanel.add(dbUtilsCard);

        // Card 2: CSV Data Import Utilities
        javax.swing.JPanel csvImportCard = new javax.swing.JPanel();
        csvImportCard.setBackground(java.awt.Color.WHITE);
        csvImportCard.setBorder(javax.swing.BorderFactory.createTitledBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 232, 240), 1),
            "CSV DATA BULK IMPORT",
            javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
            javax.swing.border.TitledBorder.DEFAULT_POSITION,
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12),
            new java.awt.Color(71, 85, 105)
        ));
        csvImportCard.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints csvGbc = new java.awt.GridBagConstraints();
        csvGbc.insets = new java.awt.Insets(15, 15, 15, 15);
        csvGbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        csvGbc.weightx = 1.0;
        csvGbc.gridx = 0;

        javax.swing.JButton btnImportCust = new javax.swing.JButton("IMPORT CUSTOMERS (CSV)");
        btnImportCust.setBackground(new java.awt.Color(99, 102, 241));
        btnImportCust.setForeground(java.awt.Color.WHITE);
        btnImportCust.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btnImportCust.setPreferredSize(new java.awt.Dimension(200, 45));
        btnImportCust.putClientProperty("JButton.buttonType", "roundRect");
        btnImportCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportCustomersActionPerformed(evt);
            }
        });
        csvGbc.gridy = 0;
        csvImportCard.add(btnImportCust, csvGbc);

        javax.swing.JButton btnImportEmp = new javax.swing.JButton("IMPORT EMPLOYEES (CSV)");
        btnImportEmp.setBackground(new java.awt.Color(99, 102, 241));
        btnImportEmp.setForeground(java.awt.Color.WHITE);
        btnImportEmp.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btnImportEmp.setPreferredSize(new java.awt.Dimension(200, 45));
        btnImportEmp.putClientProperty("JButton.buttonType", "roundRect");
        btnImportEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportEmployeesActionPerformed(evt);
            }
        });
        csvGbc.gridy = 1;
        csvImportCard.add(btnImportEmp, csvGbc);

        javax.swing.JButton btnImportPlans = new javax.swing.JButton("IMPORT PLANS (CSV)");
        btnImportPlans.setBackground(new java.awt.Color(99, 102, 241));
        btnImportPlans.setForeground(java.awt.Color.WHITE);
        btnImportPlans.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btnImportPlans.setPreferredSize(new java.awt.Dimension(200, 45));
        btnImportPlans.putClientProperty("JButton.buttonType", "roundRect");
        btnImportPlans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportPlansActionPerformed(evt);
            }
        });
        csvGbc.gridy = 2;
        csvImportCard.add(btnImportPlans, csvGbc);

        systemUtilitiesPanel.add(csvImportCard);

        // Card 3: Security & Account Utilities
        javax.swing.JPanel securityCard = new javax.swing.JPanel();
        securityCard.setBackground(java.awt.Color.WHITE);
        securityCard.setBorder(javax.swing.BorderFactory.createTitledBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 232, 240), 1),
            "SECURITY & ACCOUNT UTILITIES",
            javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
            javax.swing.border.TitledBorder.DEFAULT_POSITION,
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12),
            new java.awt.Color(71, 85, 105)
        ));
        securityCard.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints secGbc = new java.awt.GridBagConstraints();
        secGbc.insets = new java.awt.Insets(15, 15, 15, 15);
        secGbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
        secGbc.weightx = 1.0;
        secGbc.gridx = 0;

        javax.swing.JButton btnExport = new javax.swing.JButton("EXPORT FINANCIAL REPORT (CSV)");
        btnExport.setBackground(new java.awt.Color(16, 185, 129));
        btnExport.setForeground(java.awt.Color.WHITE);
        btnExport.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btnExport.setPreferredSize(new java.awt.Dimension(200, 45));
        btnExport.putClientProperty("JButton.buttonType", "roundRect");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        secGbc.gridy = 0;
        securityCard.add(btnExport, secGbc);

        javax.swing.JButton btnChangePwd = new javax.swing.JButton("CHANGE ADMIN PASSWORD");
        btnChangePwd.setBackground(new java.awt.Color(245, 158, 11));
        btnChangePwd.setForeground(java.awt.Color.WHITE);
        btnChangePwd.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btnChangePwd.setPreferredSize(new java.awt.Dimension(200, 45));
        btnChangePwd.putClientProperty("JButton.buttonType", "roundRect");
        btnChangePwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePwdActionPerformed(evt);
            }
        });
        secGbc.gridy = 1;
        securityCard.add(btnChangePwd, secGbc);

        javax.swing.JButton btnBroadcast = new javax.swing.JButton("BROADCAST EMAIL TO CUSTOMERS");
        btnBroadcast.setBackground(new java.awt.Color(139, 92, 246));
        btnBroadcast.setForeground(java.awt.Color.WHITE);
        btnBroadcast.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        btnBroadcast.setPreferredSize(new java.awt.Dimension(200, 45));
        btnBroadcast.putClientProperty("JButton.buttonType", "roundRect");
        btnBroadcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBroadcastActionPerformed(evt);
            }
        });
        secGbc.gridy = 2;
        securityCard.add(btnBroadcast, secGbc);

        systemUtilitiesPanel.add(securityCard);

        tabbedPane.addTab("System Utilities", systemUtilitiesPanel);

        // Styled outer container for tabbed pane
        javax.swing.JPanel tabContainer = new javax.swing.JPanel();
        tabContainer.setBackground(java.awt.Color.WHITE);
        tabContainer.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224), 1),
            javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)
        ));
        tabContainer.setLayout(new java.awt.BorderLayout());
        tabContainer.add(tabbedPane, java.awt.BorderLayout.CENTER);
        
        jPanel1.add(tabContainer, java.awt.BorderLayout.CENTER);

        jPanel1.revalidate();
        jPanel1.repaint();

        loadStatistics();
        loadPlanDistributionChart();
        setupLiveMonitorChart(liveChartContainer);
    }

    private javax.swing.JPanel createStatCard(String title, javax.swing.JLabel valLabel, java.awt.Color accentColor) {
        javax.swing.JPanel card = new javax.swing.JPanel();
        card.setBackground(java.awt.Color.WHITE);
        card.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224), 1),
            javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20)
        ));
        card.setLayout(new java.awt.BorderLayout());
        card.setPreferredSize(new java.awt.Dimension(0, 90)); // fixed height for stat card

        javax.swing.JPanel accentBar = new javax.swing.JPanel();
        accentBar.setBackground(accentColor);
        accentBar.setPreferredSize(new java.awt.Dimension(5, 0));
        card.add(accentBar, java.awt.BorderLayout.WEST);

        javax.swing.JPanel textPanel = new javax.swing.JPanel();
        textPanel.setOpaque(false);
        textPanel.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        javax.swing.JLabel lblTitle = new javax.swing.JLabel(title);
        lblTitle.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        lblTitle.setForeground(new java.awt.Color(99, 115, 129));
        textPanel.add(lblTitle);

        valLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22));
        valLabel.setForeground(new java.awt.Color(33, 43, 54));
        textPanel.add(valLabel);

        textPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        card.add(textPanel, java.awt.BorderLayout.CENTER);

        return card;
    }

    private void loadStatistics() {
        int activeCustomers = 0;
        double monthlyRevenue = 0.0;
        int openComplaints = 0;
        int solvedComplaints = 0;

        try {
            // 1. Total Customers
            String sqlCust = "SELECT COUNT(*) FROM customer";
            try (PreparedStatement pstCust = conn.prepareStatement(sqlCust);
                 ResultSet rsCust = pstCust.executeQuery()) {
                if (rsCust.next()) {
                    activeCustomers = rsCust.getInt(1);
                }
            }

            // 2. Total Monthly Revenue
            String sqlRev = "SELECT SUM(plan.Cost) FROM customer JOIN plan ON customer.Plan = plan.PlanName";
            try (PreparedStatement pstRev = conn.prepareStatement(sqlRev);
                 ResultSet rsRev = pstRev.executeQuery()) {
                if (rsRev.next()) {
                    monthlyRevenue = rsRev.getDouble(1);
                }
            }

            // 3. Complaints
            String sqlComp = "SELECT Action, COUNT(*) FROM complain GROUP BY Action";
            try (PreparedStatement pstComp = conn.prepareStatement(sqlComp);
                 ResultSet rsComp = pstComp.executeQuery()) {
                while (rsComp.next()) {
                    String action = rsComp.getString(1);
                    int count = rsComp.getInt(2);
                    if ("Solved".equalsIgnoreCase(action)) {
                        solvedComplaints += count;
                    } else {
                        openComplaints += count;
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        lblActiveCustomersVal.setText(String.valueOf(activeCustomers));
        lblRevenueVal.setText("Rs. " + String.format("%.2f", monthlyRevenue));
        lblComplaintsVal.setText(solvedComplaints + " / " + (openComplaints + solvedComplaints) + " Solved");
    }

    private void loadPlanDistributionChart() {
        org.jfree.data.general.DefaultPieDataset dataset = new org.jfree.data.general.DefaultPieDataset();
        try {
            String sql = "SELECT Plan, COUNT(*) FROM customer GROUP BY Plan";
            try (PreparedStatement pst = conn.prepareStatement(sql);
                 ResultSet rs = pst.executeQuery()) {
                while (rs.next()) {
                    String plan = rs.getString(1);
                    int count = rs.getInt(2);
                    if (plan == null || plan.trim().isEmpty()) {
                        plan = "No Plan";
                    }
                    dataset.setValue(plan, count);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        if (dataset.getItemCount() == 0) {
            dataset.setValue("No Customers Found", 1);
        }

        org.jfree.chart.JFreeChart chart = org.jfree.chart.ChartFactory.createPieChart(
            "Customer Plan Distribution",
            dataset,
            true,
            true,
            false
        );

        chart.setBackgroundPaint(java.awt.Color.WHITE);
        org.jfree.chart.plot.PiePlot plot = (org.jfree.chart.plot.PiePlot) chart.getPlot();
        plot.setBackgroundPaint(java.awt.Color.WHITE);
        plot.setOutlineVisible(false);
        plot.setLabelFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        plot.setLabelBackgroundPaint(new java.awt.Color(255, 255, 255, 0));
        plot.setLabelOutlinePaint(null);
        plot.setLabelShadowPaint(null);

        plot.setSectionPaint(0, new java.awt.Color(37, 99, 235));
        plot.setSectionPaint(1, new java.awt.Color(16, 185, 129));
        plot.setSectionPaint(2, new java.awt.Color(245, 158, 11));
        plot.setSectionPaint(3, new java.awt.Color(239, 68, 68));
        plot.setSectionPaint(4, new java.awt.Color(139, 92, 246));

        org.jfree.chart.ChartPanel chartPanelComponent = new org.jfree.chart.ChartPanel(chart);
        chartPanelComponent.setMinimumDrawWidth(10);
        chartPanelComponent.setMinimumDrawHeight(10);
        chartPanelComponent.setMaximumDrawWidth(3000);
        chartPanelComponent.setMaximumDrawHeight(3000);
        chartPanelComponent.setOpaque(false);

        chartPanel.removeAll();
        chartPanel.add(chartPanelComponent, java.awt.BorderLayout.CENTER);
        chartPanel.revalidate();
        chartPanel.repaint();
    }

    private javax.swing.JPanel createReadoutComponent(String title, javax.swing.JLabel valLabel, java.awt.Color color) {
        javax.swing.JPanel p = new javax.swing.JPanel();
        p.setOpaque(false);
        p.setLayout(new java.awt.GridLayout(2, 1, 2, 2));

        javax.swing.JLabel lblTitle = new javax.swing.JLabel(title, javax.swing.SwingConstants.CENTER);
        lblTitle.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 10));
        lblTitle.setForeground(new java.awt.Color(148, 163, 184));
        p.add(lblTitle);

        valLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        valLabel.setForeground(color);
        p.add(valLabel);

        return p;
    }

    private String formatSpeed(double mbps) {
        if (mbps >= 1000.0) {
            return String.format("%.2f Gbps", mbps / 1000.0);
        } else if (mbps >= 1.0) {
            return String.format("%.1f Mbps", mbps);
        } else {
            return String.format("%.1f Kbps", mbps * 1024.0);
        }
    }

    private long[] getNetworkBytes() {
        long rxBytes = 0;
        long txBytes = 0;
        try (java.io.BufferedReader reader = new java.io.BufferedReader(new java.io.FileReader("/proc/net/dev"))) {
            String line;
            reader.readLine(); // skip header 1
            reader.readLine(); // skip header 2
            while ((line = reader.readLine()) != null) {
                line = line.trim();
                String[] parts = line.split(":");
                if (parts.length < 2) continue;
                String iface = parts[0].trim();
                if (iface.equals("lo") || iface.startsWith("docker") || iface.startsWith("br-") || iface.startsWith("veth")) {
                    continue;
                }
                String[] stats = parts[1].trim().split("\\s+");
                if (stats.length >= 9) {
                    try {
                        rxBytes += Long.parseLong(stats[0]);
                        txBytes += Long.parseLong(stats[8]);
                    } catch (NumberFormatException e) {
                        // ignore
                    }
                }
            }
        } catch (Exception e) {
            return null;
        }
        return new long[]{rxBytes, txBytes};
    }

    private void setupLiveMonitorChart(javax.swing.JPanel container) {
        downloadSeries = new org.jfree.data.time.TimeSeries("Download");
        uploadSeries = new org.jfree.data.time.TimeSeries("Upload");
        downloadSeries.setMaximumItemCount(40);
        uploadSeries.setMaximumItemCount(40);

        org.jfree.data.time.TimeSeriesCollection dataset = new org.jfree.data.time.TimeSeriesCollection();
        dataset.addSeries(downloadSeries);
        dataset.addSeries(uploadSeries);

        org.jfree.chart.JFreeChart chart = org.jfree.chart.ChartFactory.createTimeSeriesChart(
            "ISP Traffic Monitor",
            "Time",
            "Bandwidth",
            dataset,
            true,
            true,
            false
        );

        chart.setBackgroundPaint(java.awt.Color.WHITE);
        org.jfree.chart.plot.XYPlot plot = (org.jfree.chart.plot.XYPlot) chart.getPlot();
        plot.setBackgroundPaint(java.awt.Color.WHITE);
        plot.setDomainGridlinePaint(new java.awt.Color(241, 245, 249));
        plot.setRangeGridlinePaint(new java.awt.Color(241, 245, 249));
        plot.setOutlineVisible(false);

        org.jfree.chart.renderer.xy.XYLineAndShapeRenderer renderer = 
            new org.jfree.chart.renderer.xy.XYLineAndShapeRenderer(true, false);
        renderer.setSeriesPaint(0, new java.awt.Color(37, 99, 235));
        renderer.setSeriesStroke(0, new java.awt.BasicStroke(2.5f));
        renderer.setSeriesPaint(1, new java.awt.Color(16, 185, 129));
        renderer.setSeriesStroke(1, new java.awt.BasicStroke(2.5f));
        plot.setRenderer(renderer);

        org.jfree.chart.axis.DateAxis domainAxis = (org.jfree.chart.axis.DateAxis) plot.getDomainAxis();
        domainAxis.setDateFormatOverride(new java.text.SimpleDateFormat("HH:mm:ss"));
        domainAxis.setTickLabelFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));
        domainAxis.setLabelFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 11));

        org.jfree.chart.axis.NumberAxis rangeAxis = (org.jfree.chart.axis.NumberAxis) plot.getRangeAxis();
        rangeAxis.setTickLabelFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));
        rangeAxis.setLabelFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 11));
        rangeAxis.setAutoRange(true); // Dynamic scale based on active speeds

        org.jfree.chart.ChartPanel chartPanelComponent = new org.jfree.chart.ChartPanel(chart);
        chartPanelComponent.setMinimumDrawWidth(10);
        chartPanelComponent.setMinimumDrawHeight(10);
        chartPanelComponent.setMaximumDrawWidth(3000);
        chartPanelComponent.setMaximumDrawHeight(3000);
        chartPanelComponent.setOpaque(false);

        container.add(chartPanelComponent, java.awt.BorderLayout.CENTER);

        // Initialize lastBytes
        lastBytes = getNetworkBytes();

        // Seed initial history
        long nowMs = System.currentTimeMillis();
        double currentDl = 45.0;
        double currentUl = 20.0;
        java.util.Random rand = new java.util.Random();
        for (int i = 40; i >= 0; i--) {
            org.jfree.data.time.Second s = new org.jfree.data.time.Second(new java.util.Date(nowMs - i * 1000));
            currentDl = Math.max(10.0, Math.min(100.0, currentDl + (rand.nextDouble() - 0.5) * 6.0));
            currentUl = Math.max(5.0, Math.min(50.0, currentUl + (rand.nextDouble() - 0.5) * 3.0));
            downloadSeries.addOrUpdate(s, currentDl);
            uploadSeries.addOrUpdate(s, currentUl);
        }

        startMonitorTimer(chart);
    }

    private void startMonitorTimer(final org.jfree.chart.JFreeChart chart) {
        if (monitorTimer != null) {
            monitorTimer.stop();
        }

        monitorTimer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            private final java.util.Random rand = new java.util.Random();

            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                long[] currentBytes = getNetworkBytes();
                double dlMbps = 0.0;
                double ulMbps = 0.0;
                boolean isReal = false;

                if (currentBytes != null && lastBytes != null) {
                    long rxDiff = currentBytes[0] - lastBytes[0];
                    long txDiff = currentBytes[1] - lastBytes[1];
                    dlMbps = (rxDiff * 8.0) / (1024.0 * 1024.0);
                    ulMbps = (txDiff * 8.0) / (1024.0 * 1024.0);
                    if (dlMbps < 0) dlMbps = 0;
                    if (ulMbps < 0) ulMbps = 0;
                    isReal = true;
                } else {
                    lastDlSim = Math.max(5.0, Math.min(150.0, lastDlSim + (rand.nextDouble() - 0.5) * 15.0));
                    lastUlSim = Math.max(2.0, Math.min(60.0, lastUlSim + (rand.nextDouble() - 0.5) * 6.0));
                    dlMbps = lastDlSim;
                    ulMbps = lastUlSim;
                }

                lastBytes = currentBytes;
                int ping = isReal ? (3 + rand.nextInt(5)) : (10 + rand.nextInt(15)); // real ping is faster!

                if (chart != null) {
                    chart.setTitle(isReal ? "ISP Real-time Traffic (Host Interface)" : "ISP Simulated Traffic (NOC Demo)");
                }

                org.jfree.data.time.Second currentSecond = new org.jfree.data.time.Second();
                if (downloadSeries != null) downloadSeries.addOrUpdate(currentSecond, dlMbps);
                if (uploadSeries != null) uploadSeries.addOrUpdate(currentSecond, ulMbps);

                if (lblLiveDl != null) lblLiveDl.setText(formatSpeed(dlMbps));
                if (lblLiveUl != null) lblLiveUl.setText(formatSpeed(ulMbps));
                if (lblLivePing != null) lblLivePing.setText(ping + " ms");
            }
        });
        monitorTimer.start();
    }

    private void stopMonitorTimer() {
        if (monitorTimer != null) {
            monitorTimer.stop();
            monitorTimer = null;
        }
    }

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Save Database Backup");
        fileChooser.setSelectedFile(new java.io.File("isp_backup.sql"));
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        javaconnect.ConnectionParams params = javaconnect.getConnectionParams();
                        String pgPassword = javaconnect.getDbPassword();
                        String pgUser = javaconnect.getDbUser();
                        ProcessBuilder pb = new ProcessBuilder("pg_dump", "-h", params.host, "-p", params.port, "-U", pgUser, "-d", params.dbName);
                        pb.environment().put("PGPASSWORD", pgPassword != null ? pgPassword : "");
                        pb.redirectOutput(fileToSave);
                        Process process = pb.start();
                        final int exitCode = process.waitFor();
                        javax.swing.SwingUtilities.invokeLater(new Runnable() {
                            public void run() {
                                if (exitCode == 0) {
                                    javax.swing.JOptionPane.showMessageDialog(Admin.this, "Database backup created successfully!");
                                } else {
                                    javax.swing.JOptionPane.showMessageDialog(Admin.this, "Backup failed with exit code: " + exitCode, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                                }
                            }
                        });
                    } catch (final Exception ex) {
                        ex.printStackTrace();
                        javax.swing.SwingUtilities.invokeLater(new Runnable() {
                            public void run() {
                                javax.swing.JOptionPane.showMessageDialog(Admin.this, "Backup error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                            }
                        });
                    }
                }
            }).start();
        }
    }

    private void btnRestoreActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Select Database Backup File to Restore");
        int userSelection = fileChooser.showOpenDialog(this);
        if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File fileToOpen = fileChooser.getSelectedFile();
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to restore? This will overwrite the current database data!", 
                "Confirm Restore", javax.swing.JOptionPane.YES_NO_OPTION);
            
            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            javaconnect.ConnectionParams params = javaconnect.getConnectionParams();
                            String pgPassword = javaconnect.getDbPassword();
                            String pgUser = javaconnect.getDbUser();
                            ProcessBuilder pb = new ProcessBuilder("psql", "-h", params.host, "-p", params.port, "-U", pgUser, "-d", params.dbName);
                            pb.environment().put("PGPASSWORD", pgPassword != null ? pgPassword : "");
                            pb.redirectInput(fileToOpen);
                            Process process = pb.start();
                            final int exitCode = process.waitFor();
                            javax.swing.SwingUtilities.invokeLater(new Runnable() {
                                public void run() {
                                    if (exitCode == 0) {
                                        javax.swing.JOptionPane.showMessageDialog(Admin.this, "Database restored successfully!");
                                        loadStatistics();
                                        loadPlanDistributionChart();
                                    } else {
                                        javax.swing.JOptionPane.showMessageDialog(Admin.this, "Restore failed with exit code: " + exitCode, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                                    }
                                }
                            });
                        } catch (final Exception ex) {
                            ex.printStackTrace();
                            javax.swing.SwingUtilities.invokeLater(new Runnable() {
                                public void run() {
                                    javax.swing.JOptionPane.showMessageDialog(Admin.this, "Restore error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                                }
                            });
                        }
                    }
                }).start();
            }
        }
    }

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Export Financial Report");
        fileChooser.setSelectedFile(new java.io.File("financial_report.csv"));
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
            final java.io.File fileToSave = fileChooser.getSelectedFile();
            new Thread(new Runnable() {
                @Override
                public void run() {
                    String sql = "SELECT customer.ID, customer.Name, customer.Plan, plan.Cost " +
                                 "FROM customer LEFT JOIN plan ON customer.Plan = plan.PlanName";
                    try (java.sql.Connection localConn = javaconnect.ConnecrDb();
                         PreparedStatement pst = localConn.prepareStatement(sql);
                         ResultSet rs = pst.executeQuery();
                         java.io.PrintWriter pw = new java.io.PrintWriter(new java.io.FileWriter(fileToSave))) {
                        
                        pw.println("Customer ID,Customer Name,Active Plan,Base Cost,CGST (9%),SGST (9%),Total Monthly Dues");
                        double grandTotal = 0.0;
                        int count = 0;
                        
                        while (rs.next()) {
                            int id = rs.getInt("ID");
                            String name = rs.getString("Name");
                            String plan = rs.getString("Plan");
                            double cost = rs.getDouble("Cost");
                            
                            double cgst = cost * 0.09;
                            double sgst = cost * 0.09;
                            double total = cost + cgst + sgst;
                            grandTotal += total;
                            count++;
                            
                            pw.println(id + ",\"" + name.replace("\"", "\"\"") + "\",\"" + 
                                       (plan != null ? plan : "No Plan") + "\"," + 
                                       cost + "," + cgst + "," + sgst + "," + total);
                        }
                        
                        pw.println();
                        pw.println("Summary Statistics");
                        pw.println("Total Customers Count," + count);
                        pw.println("Grand Total Revenue (inc. Tax)," + grandTotal);
                        
                        javax.swing.SwingUtilities.invokeLater(new Runnable() {
                            public void run() {
                                javax.swing.JOptionPane.showMessageDialog(Admin.this, "Financial report exported successfully to " + fileToSave.getName());
                            }
                        });
                    } catch (final Exception ex) {
                        ex.printStackTrace();
                        javax.swing.SwingUtilities.invokeLater(new Runnable() {
                            public void run() {
                                javax.swing.JOptionPane.showMessageDialog(Admin.this, "Export error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                            }
                        });
                    }
                }
            }).start();
        }
    }

    private void btnChangePwdActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(3, 2, 10, 10));
        javax.swing.JPasswordField txtCurrent = new javax.swing.JPasswordField();
        javax.swing.JPasswordField txtNew = new javax.swing.JPasswordField();
        javax.swing.JPasswordField txtConfirm = new javax.swing.JPasswordField();

        panel.add(new javax.swing.JLabel("Current Password:"));
        panel.add(txtCurrent);
        panel.add(new javax.swing.JLabel("New Password:"));
        panel.add(txtNew);
        panel.add(new javax.swing.JLabel("Confirm New Password:"));
        panel.add(txtConfirm);

        int result = javax.swing.JOptionPane.showConfirmDialog(this, panel, "Change Admin Password",
            javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);

        if (result == javax.swing.JOptionPane.OK_OPTION) {
            String currentPwd = new String(txtCurrent.getPassword());
            String newPwd = new String(txtNew.getPassword());
            String confirmPwd = new String(txtConfirm.getPassword());

            if (currentPwd.trim().isEmpty() || newPwd.trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Fields cannot be empty!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!newPwd.equals(confirmPwd)) {
                javax.swing.JOptionPane.showMessageDialog(this, "New passwords do not match!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                String sql = "SELECT password FROM admin WHERE username='admin'";
                String storedHash = null;
                try (PreparedStatement pst = conn.prepareStatement(sql);
                     ResultSet rs = pst.executeQuery()) {
                    if (rs.next()) {
                        storedHash = rs.getString(1);
                    }
                }

                boolean auth = false;
                if (storedHash != null) {
                    if (storedHash.contains(":")) {
                        auth = PasswordHasher.checkPassword(currentPwd, storedHash);
                    } else {
                        auth = storedHash.equals(currentPwd);
                    }
                }

                if (!auth) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Incorrect current password!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }

                String newHash = PasswordHasher.hashPassword(newPwd);
                String updateSql = "UPDATE admin SET password=? WHERE username='admin'";
                try (PreparedStatement updatePst = conn.prepareStatement(updateSql)) {
                    updatePst.setString(1, newHash);
                    updatePst.executeUpdate();
                }

                javax.swing.JOptionPane.showMessageDialog(this, "Admin password updated successfully!");

            } catch (Exception ex) {
                ex.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error changing password: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void btnBroadcastActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout(10, 10));
        
        javax.swing.JPanel topPanel = new javax.swing.JPanel(new java.awt.BorderLayout(5, 5));
        topPanel.add(new javax.swing.JLabel("Subject:"), java.awt.BorderLayout.WEST);
        javax.swing.JTextField txtSubject = new javax.swing.JTextField();
        topPanel.add(txtSubject, java.awt.BorderLayout.CENTER);
        panel.add(topPanel, java.awt.BorderLayout.NORTH);
        
        javax.swing.JPanel bodyPanel = new javax.swing.JPanel(new java.awt.BorderLayout(5, 5));
        bodyPanel.add(new javax.swing.JLabel("Message Body:"), java.awt.BorderLayout.NORTH);
        javax.swing.JTextArea txtBody = new javax.swing.JTextArea(8, 30);
        txtBody.setLineWrap(true);
        txtBody.setWrapStyleWord(true);
        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(txtBody);
        bodyPanel.add(scroll, java.awt.BorderLayout.CENTER);
        panel.add(bodyPanel, java.awt.BorderLayout.CENTER);

        int result = javax.swing.JOptionPane.showConfirmDialog(this, panel, "Broadcast Email to All Customers",
            javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);

        if (result == javax.swing.JOptionPane.OK_OPTION) {
            final String subject = txtSubject.getText().trim();
            final String bodyTemplate = txtBody.getText().trim();

            if (subject.isEmpty() || bodyTemplate.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Subject and Message Body cannot be empty!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            new Thread(new Runnable() {
                @Override
                public void run() {
                    int successCount = 0;
                    int totalCount = 0;
                    try (java.sql.Connection localConn = javaconnect.ConnecrDb()) {
                        if (localConn == null) throw new Exception("Database connection offline");
                        String sql = "SELECT Name, email FROM customer";
                        try (PreparedStatement pst = localConn.prepareStatement(sql);
                             ResultSet rs = pst.executeQuery()) {
                            
                            while (rs.next()) {
                                String name = rs.getString("Name");
                                String email = rs.getString("email");
                                if (email != null && !email.trim().isEmpty()) {
                                    totalCount++;
                                    try {
                                        String personalizedBody = "Dear " + name + ",\n\n" + bodyTemplate;
                                        EmailUtility.sendEmail(email.trim(), subject, personalizedBody, null);
                                        successCount++;
                                    } catch (Exception ex) {
                                        ex.printStackTrace();
                                    }
                                }
                            }
                        }
                        
                        final int finalSuccess = successCount;
                        final int finalTotal = totalCount;
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            public void run() {
                                if (EmailUtility.isSmtpConfigured()) {
                                    javax.swing.JOptionPane.showMessageDialog(Admin.this, 
                                        "Broadcast complete!\nSent successfully to " + finalSuccess + " out of " + finalTotal + " customers.");
                                } else {
                                    javax.swing.JOptionPane.showMessageDialog(Admin.this, 
                                        "Broadcast fallback simulation complete!\nPrinted " + finalTotal + " email bodies to log console (SMTP unconfigured).");
                                }
                            }
                        });
                        
                    } catch (final Exception ex) {
                        ex.printStackTrace();
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            public void run() {
                                javax.swing.JOptionPane.showMessageDialog(Admin.this, "Error in broadcast: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                            }
                        });
                    }
                }
            }).start();
        }
    }

    private String[] parseCSVLine(String line) {
        return line.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)");
    }

    private String cleanCSVField(String field) {
        if (field == null) return "";
        field = field.trim();
        if (field.startsWith("\"") && field.endsWith("\"")) {
            field = field.substring(1, field.length() - 1);
        }
        return field.replace("\"\"", "\"").trim();
    }

    private void btnImportCustomersActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Select Customers CSV File to Import");
        int userSelection = fileChooser.showOpenDialog(this);
        if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileChooser.getSelectedFile();
            new Thread(new Runnable() {
                @Override
                public void run() {
                    int imported = 0;
                    int failed = 0;
                    String sql = "INSERT INTO customer (ID, Name, Contact, Sex, Purpose, Address, Plan, email) " +
                                 "VALUES (?, ?, ?, ?, ?, ?, ?, ?) " +
                                 "ON CONFLICT (ID) DO UPDATE SET " +
                                 "  Name = EXCLUDED.Name, " +
                                 "  Contact = EXCLUDED.Contact, " +
                                 "  Sex = EXCLUDED.Sex, " +
                                 "  Purpose = EXCLUDED.Purpose, " +
                                 "  Address = EXCLUDED.Address, " +
                                 "  Plan = EXCLUDED.Plan, " +
                                 "  email = EXCLUDED.email";
                                 
                    java.sql.Connection localConn = null;
                    try {
                        localConn = javaconnect.ConnecrDb();
                        if (localConn == null) throw new Exception("Database connection offline");
                        localConn.setAutoCommit(false);

                        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(file));
                             PreparedStatement pst = localConn.prepareStatement(sql)) {
                            
                            String line;
                            boolean isHeader = true;
                            while ((line = br.readLine()) != null) {
                                if (line.trim().isEmpty()) continue;
                                String[] fields = parseCSVLine(line);
                                if (isHeader) {
                                    isHeader = false;
                                    try {
                                        Integer.parseInt(cleanCSVField(fields[0]));
                                    } catch (NumberFormatException e) {
                                        continue;
                                    }
                                }
                                
                                if (fields.length < 7) {
                                    failed++;
                                    continue;
                                }
                                
                                try {
                                    pst.setInt(1, Integer.parseInt(cleanCSVField(fields[0])));
                                    pst.setString(2, cleanCSVField(fields[1]));
                                    pst.setString(3, cleanCSVField(fields[2]));
                                    pst.setString(4, cleanCSVField(fields[3]).toUpperCase()); // Sex
                                    pst.setString(5, cleanCSVField(fields[4]).toUpperCase()); // Purpose
                                    pst.setString(6, cleanCSVField(fields[5])); // Address
                                    pst.setString(7, cleanCSVField(fields[6])); // Plan
                                    pst.setString(8, fields.length >= 8 ? cleanCSVField(fields[7]) : ""); // email
                                    pst.executeUpdate();
                                    imported++;
                                } catch (Exception ex) {
                                    ex.printStackTrace();
                                    failed++;
                                }
                            }
                            localConn.commit();
                        } catch (Exception ex) {
                            localConn.rollback();
                            throw ex;
                        }
                        
                        final int finalImported = imported;
                        final int finalFailed = failed;
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            public void run() {
                                javax.swing.JOptionPane.showMessageDialog(Admin.this, 
                                    "Customers CSV Import Complete!\nSuccessfully imported/updated: " + finalImported + "\nFailed/skipped: " + finalFailed);
                                loadStatistics();
                                loadPlanDistributionChart();
                            }
                        });
                        
                    } catch (final Exception ex) {
                        ex.printStackTrace();
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            public void run() {
                                javax.swing.JOptionPane.showMessageDialog(Admin.this, "Import error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                            }
                        });
                    } finally {
                        if (localConn != null) {
                            try { localConn.setAutoCommit(true); } catch (Exception e) {}
                            try { localConn.close(); } catch (Exception e) {}
                        }
                    }
                }
            }).start();
        }
    }

    private void btnImportEmployeesActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Select Employees CSV File to Import");
        int userSelection = fileChooser.showOpenDialog(this);
        if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileChooser.getSelectedFile();
            new Thread(new Runnable() {
                @Override
                public void run() {
                    int imported = 0;
                    int failed = 0;
                    String sql = "INSERT INTO employee (ID, Name, Contact, JoinDate, Address, LeaveDate) " +
                                 "VALUES (?, ?, ?, ?, ?, ?) " +
                                 "ON CONFLICT (ID) DO UPDATE SET " +
                                 "  Name = EXCLUDED.Name, " +
                                 "  Contact = EXCLUDED.Contact, " +
                                 "  JoinDate = EXCLUDED.JoinDate, " +
                                 "  Address = EXCLUDED.Address, " +
                                 "  LeaveDate = EXCLUDED.LeaveDate";
                                 
                    java.sql.Connection localConn = null;
                    try {
                        localConn = javaconnect.ConnecrDb();
                        if (localConn == null) throw new Exception("Database connection offline");
                        localConn.setAutoCommit(false);

                        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(file));
                             PreparedStatement pst = localConn.prepareStatement(sql)) {
                            
                            String line;
                            boolean isHeader = true;
                            while ((line = br.readLine()) != null) {
                                if (line.trim().isEmpty()) continue;
                                String[] fields = parseCSVLine(line);
                                if (isHeader) {
                                    isHeader = false;
                                    try {
                                        Integer.parseInt(cleanCSVField(fields[0]));
                                    } catch (NumberFormatException e) {
                                        continue;
                                    }
                                }
                                
                                if (fields.length < 5) {
                                    failed++;
                                    continue;
                                }
                                
                                try {
                                    pst.setInt(1, Integer.parseInt(cleanCSVField(fields[0])));
                                    pst.setString(2, cleanCSVField(fields[1]));
                                    pst.setString(3, cleanCSVField(fields[2]));
                                    pst.setString(4, cleanCSVField(fields[3]));
                                    pst.setString(5, cleanCSVField(fields[4]));
                                    String leaveVal = fields.length >= 6 ? cleanCSVField(fields[5]) : null;
                                    if (leaveVal != null && (leaveVal.equalsIgnoreCase("null") || leaveVal.isEmpty())) {
                                        leaveVal = null;
                                    }
                                    pst.setString(6, leaveVal);
                                    pst.executeUpdate();
                                    imported++;
                                } catch (Exception ex) {
                                    ex.printStackTrace();
                                    failed++;
                                }
                            }
                            localConn.commit();
                        } catch (Exception ex) {
                            localConn.rollback();
                            throw ex;
                        }
                        
                        final int finalImported = imported;
                        final int finalFailed = failed;
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            public void run() {
                                javax.swing.JOptionPane.showMessageDialog(Admin.this, 
                                    "Employees CSV Import Complete!\nSuccessfully imported/updated: " + finalImported + "\nFailed/skipped: " + finalFailed);
                            }
                        });
                        
                    } catch (final Exception ex) {
                        ex.printStackTrace();
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            public void run() {
                                javax.swing.JOptionPane.showMessageDialog(Admin.this, "Import error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                            }
                        });
                    } finally {
                        if (localConn != null) {
                            try { localConn.setAutoCommit(true); } catch (Exception e) {}
                            try { localConn.close(); } catch (Exception e) {}
                        }
                    }
                }
            }).start();
        }
    }

    private void btnImportPlansActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Select Plans CSV File to Import");
        int userSelection = fileChooser.showOpenDialog(this);
        if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileChooser.getSelectedFile();
            new Thread(new Runnable() {
                @Override
                public void run() {
                    int imported = 0;
                    int failed = 0;
                    String sql = "INSERT INTO plan (ID, PlanName, Cost, Speed, Duration) " +
                                 "VALUES (?, ?, ?, ?, ?) " +
                                 "ON CONFLICT (ID) DO UPDATE SET " +
                                 "  PlanName = EXCLUDED.PlanName, " +
                                 "  Cost = EXCLUDED.Cost, " +
                                 "  Speed = EXCLUDED.Speed, " +
                                 "  Duration = EXCLUDED.Duration";
                                 
                    java.sql.Connection localConn = null;
                    try {
                        localConn = javaconnect.ConnecrDb();
                        if (localConn == null) throw new Exception("Database connection offline");
                        localConn.setAutoCommit(false);

                        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(file));
                             PreparedStatement pst = localConn.prepareStatement(sql)) {
                            
                            String line;
                            boolean isHeader = true;
                            while ((line = br.readLine()) != null) {
                                if (line.trim().isEmpty()) continue;
                                String[] fields = parseCSVLine(line);
                                if (isHeader) {
                                    isHeader = false;
                                    try {
                                        Integer.parseInt(cleanCSVField(fields[0]));
                                    } catch (NumberFormatException e) {
                                        continue;
                                    }
                                }
                                
                                if (fields.length < 5) {
                                    failed++;
                                    continue;
                                }
                                
                                try {
                                    pst.setInt(1, Integer.parseInt(cleanCSVField(fields[0])));
                                    pst.setString(2, cleanCSVField(fields[1]));
                                    pst.setInt(3, Integer.parseInt(cleanCSVField(fields[2])));
                                    pst.setString(4, cleanCSVField(fields[3]));
                                    pst.setString(5, cleanCSVField(fields[4]));
                                    pst.executeUpdate();
                                    imported++;
                                } catch (Exception ex) {
                                    ex.printStackTrace();
                                    failed++;
                                }
                            }
                            localConn.commit();
                        } catch (Exception ex) {
                            localConn.rollback();
                            throw ex;
                        }
                        
                        final int finalImported = imported;
                        final int finalFailed = failed;
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            public void run() {
                                javax.swing.JOptionPane.showMessageDialog(Admin.this, 
                                    "Plans CSV Import Complete!\nSuccessfully imported/updated: " + finalImported + "\nFailed/skipped: " + finalFailed);
                                loadStatistics();
                                loadPlanDistributionChart();
                            }
                        });
                        
                    } catch (final Exception ex) {
                        ex.printStackTrace();
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            public void run() {
                                javax.swing.JOptionPane.showMessageDialog(Admin.this, "Import error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                            }
                        });
                    } finally {
                        if (localConn != null) {
                            try { localConn.setAutoCommit(true); } catch (Exception e) {}
                            try { localConn.close(); } catch (Exception e) {}
                        }
                    }
                }
            }).start();
        }
    }

    public void inheritWindowState(javax.swing.JFrame parent) {
        if (parent != null) {
            int state = parent.getExtendedState();
            if ((state & javax.swing.JFrame.MAXIMIZED_BOTH) == javax.swing.JFrame.MAXIMIZED_BOTH) {
                this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
            } else {
                this.setBounds(parent.getBounds());
            }
        }
    }
}
