package com.synaptix.isp;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Hunter Fox
 */
public class Home extends javax.swing.JFrame {

Connection conn;
PreparedStatement pst;
ResultSet rs;
    public Home() {
        super("Home Page");
        initComponents();
        conn=javaconnect.ConnecrDb();
        showDate();
        showTime();
    }
    
    void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("YYYY-MM-dd");
        dateLab.setText(s.format(d));
    }
    
    void showTime(){
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
        timeLab.setText(s.format(d));
            }
        }).start();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dateLab = new javax.swing.JTextField();
        timeLab = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        user1 = new javax.swing.JPasswordField();
        logBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SynapTix Broadband - Admin Login");
        setResizable(true);

        // Main Panel (Background) - GridBagLayout for centering
        jPanel1.setBackground(new java.awt.Color(240, 244, 248));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        // Header Panel (Top Bar)
        javax.swing.JPanel headerPanel = new javax.swing.JPanel();
        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 25, 15, 25));
        headerPanel.setLayout(new java.awt.BorderLayout());

        // Header Left (Logo + Title)
        javax.swing.JPanel headerLeft = new javax.swing.JPanel();
        headerLeft.setOpaque(false);
        headerLeft.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 0));
        
        java.net.URL logoUrl = getClass().getResource("/logomain.png");
        if (logoUrl != null) {
            javax.swing.ImageIcon logoIcon = new javax.swing.ImageIcon(logoUrl);
            java.awt.Image scaledLogo = logoIcon.getImage().getScaledInstance(55, 55, java.awt.Image.SCALE_SMOOTH);
            jLabel9.setIcon(new javax.swing.ImageIcon(scaledLogo));
        } else {
            jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logomain.png")));
        }
        headerLeft.add(jLabel9);

        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22));
        jLabel1.setForeground(new java.awt.Color(33, 43, 54));
        jLabel1.setText("SYNAPTIX BROADBAND");
        headerLeft.add(jLabel1);
        headerPanel.add(headerLeft, java.awt.BorderLayout.WEST);

        // Header Right (Date & Time)
        javax.swing.JPanel headerRight = new javax.swing.JPanel();
        headerRight.setOpaque(false);
        headerRight.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 5));

        jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        jLabel2.setForeground(new java.awt.Color(99, 115, 129));
        jLabel2.setText("Date:");
        headerRight.add(jLabel2);

        dateLab.setEditable(false);
        dateLab.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        dateLab.setColumns(8);
        headerRight.add(dateLab);

        jLabel3.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        jLabel3.setForeground(new java.awt.Color(99, 115, 129));
        jLabel3.setText("Time:");
        headerRight.add(jLabel3);

        timeLab.setEditable(false);
        timeLab.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        timeLab.setColumns(8);
        headerRight.add(timeLab);
        headerPanel.add(headerRight, java.awt.BorderLayout.EAST);

        // Login Card Panel
        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224), 1),
            javax.swing.BorderFactory.createEmptyBorder(30, 40, 30, 40)
        ));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.insets = new java.awt.Insets(0, 0, 20, 0);
        gbc.anchor = java.awt.GridBagConstraints.CENTER;

        // User Avatar Icon & Header
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/account.png")));
        jPanel2.add(jLabel7, gbc);

        gbc.gridy = 1;
        jLabel4.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 20));
        jLabel4.setForeground(new java.awt.Color(33, 43, 54));
        jLabel4.setText("ADMIN LOGIN");
        jPanel2.add(jLabel4, gbc);

        // Grid spacing for form fields
        gbc.gridwidth = 1;
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;

        // Username Label & Field
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 0.3;
        gbc.insets = new java.awt.Insets(10, 0, 10, 10);
        jLabel5.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        jLabel5.setForeground(new java.awt.Color(99, 115, 129));
        jLabel5.setText("Username:");
        jPanel2.add(jLabel5, gbc);

        gbc.gridx = 1;
        gbc.weightx = 0.7;
        gbc.insets = new java.awt.Insets(10, 0, 10, 0);
        user.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        user.setPreferredSize(new java.awt.Dimension(180, 32));
        jPanel2.add(user, gbc);

        // Password Label & Field
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 0.3;
        gbc.insets = new java.awt.Insets(10, 0, 20, 10);
        jLabel6.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        jLabel6.setForeground(new java.awt.Color(99, 115, 129));
        jLabel6.setText("Password:");
        jPanel2.add(jLabel6, gbc);

        gbc.gridx = 1;
        gbc.weightx = 0.7;
        gbc.insets = new java.awt.Insets(10, 0, 20, 0);
        user1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        user1.setPreferredSize(new java.awt.Dimension(180, 32));
        jPanel2.add(user1, gbc);

        // Login Button
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.insets = new java.awt.Insets(10, 0, 0, 0);
        logBtn.setBackground(new java.awt.Color(37, 99, 235));
        logBtn.putClientProperty("JButton.buttonType", "roundRect");
        logBtn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        logBtn.setForeground(new java.awt.Color(255, 255, 255));
        logBtn.setText("Log In");
        logBtn.setPreferredSize(new java.awt.Dimension(260, 40));
        logBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBtnActionPerformed(evt);
            }
        });
        jPanel2.add(logBtn, gbc);

        // Layout assemblies in main content
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);
        
        java.awt.GridBagConstraints mainGbc = new java.awt.GridBagConstraints();
        mainGbc.gridx = 0;
        mainGbc.gridy = 0;
        mainGbc.insets = new java.awt.Insets(40, 40, 40, 40);
        mainGbc.anchor = java.awt.GridBagConstraints.CENTER;
        jPanel1.add(jPanel2, mainGbc);
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setSize(960, 680);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dateLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateLabActionPerformed

    private void logBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBtnActionPerformed
        String username = user.getText();
        String enteredPassword = new String(user1.getPassword());
        String sql = "select * from admin where username=?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, username);
            rs = pst.executeQuery();
            if (rs.next()) {
                String storedPassword = rs.getString("password");
                int userId = rs.getInt("id");
                boolean authenticated = false;
                boolean needsMigration = false;

                if (storedPassword.contains(":")) {
                    authenticated = PasswordHasher.checkPassword(enteredPassword, storedPassword);
                } else {
                    // Fallback to plaintext for legacy passwords
                    if (storedPassword.equals(enteredPassword)) {
                        authenticated = true;
                        needsMigration = true;
                    }
                }

                if (authenticated) {
                    if (needsMigration) {
                        // Migrate legacy password to hashed password
                        String newHash = PasswordHasher.hashPassword(enteredPassword);
                        try (PreparedStatement updatePst = conn.prepareStatement("UPDATE admin SET password=? WHERE id=?")) {
                            updatePst.setString(1, newHash);
                            updatePst.setInt(2, userId);
                            updatePst.executeUpdate();
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                    }
                    rs.close();
                    pst.close();
                    try { if (conn != null) conn.close(); } catch (Exception ex) {}
                    Admin ob = new Admin();
                    ob.inheritWindowState(this);
                    ob.setVisible(true);
                    final javax.swing.JFrame self = this;
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            self.dispose();
                        }
                    });
                } else {
                    JOptionPane.showMessageDialog(null, "Wrong Username Or Password....!!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Wrong Username Or Password....!!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_logBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UIUtils.applyPremiumTheme();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logBtn;
    private javax.swing.JTextField timeLab;
    private javax.swing.JTextField user;
    private javax.swing.JPasswordField user1;
    // End of variables declaration//GEN-END:variables

    public void inheritWindowState(javax.swing.JFrame parent) {
        if (parent != null) {
            int state = parent.getExtendedState();
            if ((state & javax.swing.JFrame.MAXIMIZED_BOTH) == javax.swing.JFrame.MAXIMIZED_BOTH) {
                this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
            } else {
                this.setBounds(parent.getBounds());
            }
        }
    }
}
